export const products = [
    {
        id: 1,
        name: "Air diffuser",
        avatar: 'https://robohash.org/airdiffuser.png?size=50x50&set=set1',
		boosted: true,
		date: "31 Mar, 2099",
        price: 'USD 21,640',
        category: "Home decor",
        tags: ["Valentine", "Home", "three", "four", "five"],
        clicks: 500000,
        saves: 300,
        status: "live"
    },
    {
        id: 2,
        name: "Wrist watch",
        avatar: 'https://robohash.org/wristwatch.png?size=50x50&set=set1',
		boosted: true,
		date: "31 Mar, 2099",
        price: 'USD 21,640',
        category: "Jewelry & watches",
        tags: ["Valentine", "Home"],
        clicks: 500,
        saves: 300,
        status: "live"
    },
    {
        id: 3,
        name: "Birkins handbag a very long list of somethinggdfdf",
        avatar: 'https://robohash.org/bag.png?size=50x50&set=set1',
		boosted: false,
		date: "31 Mar, 2099",
        price: 'USD 21,640',
        category: "Home decor",
        tags: ["Valentine"],
        clicks: 500,
        saves: 300,
        status: "paused"
    },
    {
        id: 4,
        name: "MTN HYNETFLEX",
        avatar: 'https://robohash.org/mtn.png?size=50x50&set=set1',
		boosted: true,
		date: "31 Mar, 2099",
        price: 'USD 21,640',
        category: "technology",
        // tags: ["Valentine"],
        clicks: 500,
        saves: 300,
        status: "paused"
    },
    {
        id: 5,
        name: "Birkins handbag a very long list of somethinggdfdf",
        avatar: 'https://robohash.org/bag.png?size=50x50&set=set1',
		boosted: false,
		date: "31 Mar, 2099",
        price: 'USD 21,640',
        category: "Home decor",
        tags: ["Valentine"],
        clicks: 500,
        saves: 300,
        status: "paused"
    },
    {
        id: 6,
        name: "Nike Airforce shoes",
        avatar: 'https://robohash.org/shoes.png?size=50x50&set=set1',
		boosted: true,
		date: "31 Mar, 2099",
        price: 'USD 21,640',
        category: "technology",
        tags: ["Valentine"],
        clicks: 500,
        saves: 300,
        status: "live"
    },
    {
        id: 7,
        name: "Birkins handbag a very long list of somethinggdfdf",
        avatar: 'https://robohash.org/bag.png?size=50x50&set=set1',
		boosted: false,
		date: "31 Mar, 2099",
        price: 'USD 21,640',
        category: "Home decor",
        tags: ["Valentine"],
        clicks: 500,
        saves: 300,
        status: "live"
    },
    {
        id: 8,
        name: "MTN HYNETFLEX",
        avatar: 'https://robohash.org/mtn.png?size=50x50&set=set1',
		boosted: true,
		date: "31 Mar, 2099",
        price: 'USD 21,640',
        category: "technology",
        // tags: ["Valentine"],
        clicks: 500,
        saves: 300,
        status: "paused"
    },
    {
        id: 9,
        name: "Birkins handbag a very long list of somethinggdfdf",
        avatar: 'https://robohash.org/bag.png?size=50x50&set=set1',
		boosted: false,
		date: "31 Mar, 2099",
        price: 'USD 21,640',
        category: "Home decor",
        tags: ["Valentine"],
        clicks: 500,
        saves: 300,
        status: "live"
    },
    {
        id: 10,
        name: "Nike Airforce shoes",
        avatar: 'https://robohash.org/shoes.png?size=50x50&set=set1',
		boosted: true,
		date: "31 Mar, 2099",
        price: 'USD 21,640',
        category: "technology",
        tags: ["Valentine"],
        clicks: 500,
        saves: 300,
        status: "paused"
    },

];